### PR TITLE
Fix: BO ps_emailsubscription not multistore compliant

### LINKED ISSUE #36152: BO ps_emailsubscription not multistore compliant
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the BO, on the configuration page of ps_emailsubscription, the list under the section `Newsletter registrations` shows the customers of all shops, disregarding the current shop context or the permissions of the employee.

### Expected behavior

In a multishop installation, when a shop is selected, only the newsletter regitstrations of that show must be displayed.

### Steps to reproduce

Prerequisite:
- Multishop activated
- At least 2 shops
- At least one customer that registered for newsletters in each shop
   
Steps to reproduce
1. Select a particular shop in the shops menu
2. Go to `Module manager`, search ps_emailsubscription, click on configure
3. Scroll down to `Newsletter registrations
4. You see the registrations of all shops

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_emailsubscription 2.8.2

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

### PR DESCRIPTION
**Pull request by Codencode**
Filter newsletter subscribers by selected shop context in module configuration

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This PR updates the `getSubscribers()` method to filter newsletter subscribers (both customers and non-customers) according to the current multishop context defined in the module configuration.<br/>If the multishop feature is active, only subscribers belonging to the current shop or shop group are displayed.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#36152
| How to test?  | 1. Enable the **Multishop** feature and create a second shop. <br/>2. Add newsletter emails in both shops — using the newsletter module and customer registration form. <br/> 3. Open the module configuration page and check that the subscriber list changes according to the selected shop context.

### CODE REVIEW

**Comment by Hlavtox** [comment]
@Codencode I will approve it, but just to double check - don't we have something like `getShopIdsInContext` that would always return an array with ids?

Your way works no problem, but seems very verbose for an often used thing, but maybe it's the only way. :-)

cc @kpodemski

File: ps_emailsubscription.php [hunk 1]
```diff
@@ -505,6 +505,19 @@ public function newsletterRegistration($hookName = null)
 
     public function getSubscribers()
     {
+        $shopIds = [];
+        if (Configuration::get('PS_MULTISHOP_FEATURE_ACTIVE')) {
```
Comment (kpodemski) [inline ps_emailsubscription.php]:
```suggestion
        if (Shop::isFeatureActive()) {
```

**Comment by kpodemski** [comment]
Hello @Codencode 

Thanks for the PR. I think you can use `Shop::getContextListShopID()`

**Comment by Codencode** [comment]
@kpodemski @Hlavtox You are absolutely right, I made a hasty edit :)
In any case, I have made the changes.

File: ps_emailsubscription.php (hunk 1 above)
Comment (Codencode) [reply ps_emailsubscription.php]: Done

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Codencode,

I tested your PR and it's good for me! :tada: 

Thanks!


https://github.com/user-attachments/assets/0773fd77-d1ea-4ed5-9353-94389cd73e48

**Review by paulnoelcholot — APPROVED** [review]
